from app.prompts.ocr_prompts import (
    DOCUMENT_CLASSIFICATION_PROMPT,
    VERBATIM_OCR_PROMPT,
    SPECIALIZED_HANDWRITING_OCR_PROMPT,
    STRUCTURED_EXTRACTION_PROMPTS
)

__all__ = [
    "DOCUMENT_CLASSIFICATION_PROMPT",
    "VERBATIM_OCR_PROMPT",
    "SPECIALIZED_HANDWRITING_OCR_PROMPT",
    "STRUCTURED_EXTRACTION_PROMPTS"
]
